# Oliver Kullmann, 4.10.2012 (Swansea)

html_dir=csoliver@cs-svr1.swansea.ac.uk:public_html/ProgrammingJava201213
slides_dir=$(html_dir)/Slides

.PHONY : all public public-html clean

all : public

public : public-html

public-html :
	scp index.html $(html_dir)


clean :
