#!/bin/bash
# Oliver Kullmann, 19.11.2011 (Swansea)

set -o errexit
set -o nounset

script_name="TestSort4"
version_number=0.1.2

programs=${programs:-*/Sort4.class}
testcases=${testcases:-../TestcasesSort4}

for P in ${programs}; do
  dir=$(dirname ${P})
  echo ${dir}
  cd ${dir}
  errors=0
  while read line; do
    input=${line}
    computed_result=$(java Sort4 ${input})
    read line
    expected_result=${line}
    if [[ "${computed_result}" != "${expected_result}" ]]; then
      echo -e " False result on input \"${input}\"."
      let "++errors"
    fi
  done < ${testcases}
  echo "errors=${errors}"
  echo
  cd ..
done
