#!/bin/bash
# Oliver Kullmann, 27.11.2011 (Swansea)

set -o errexit
set -o nounset

script_name="TestModularPower"
version_number=0.0.9

testee=ModularPower
programs=${programs:-*/${testee}.class}
testcases=${testcases:-../Testcases${testee}}

for P in ${programs}; do
  dir=$(dirname ${P})
  echo ${dir}
  cd ${dir}
  errors=0
  while read line; do
    input=${line}
    computed_result=$(java ${testee} ${input})
    read line
    expected_result=${line}
    if [[ "${computed_result}" != "${expected_result}" ]]; then
      echo -e " False result on input \"${input}\"."
      let "++errors"
    fi
  done < ${testcases}
  echo "errors=${errors}"
  echo
  cd ..
done
