#!/bin/bash
# Oliver Kullmann, 2.12.2012 (Swansea)

# Usage:

# ProduceTestResults testcases_dir testresults_dir

# Runs "program=Functions" with every file in testcases_dir put as command-line
# arguments, placing the results in a file with the same name in
# directory testresults_dir

set -o errexit
set -o nounset
set -o pipefail

script_name="ProduceTestResults"
version_number=0.2

errormsg="ERROR[${script_name}]:"

if [[ $# != 2 ]]; then
  echo "${errormsg} Precisely two arguments are needed:
 testcases_dir testresults_dir"
  exit 1
fi

testcases_dir=$1
testresults_dir=$2
program=Functions

for T in ${testcases_dir}/*; do
  B=$(basename $T)
  echo "RUNNING $B"
set +o errexit
  if [[ -s $T ]]; then
    cat $T | xargs bash -c 'java -ea '"${program}"' "$@"; echo "$?" > AUSGABE ' -
  else
    java -ea ${program}
    echo "$?" > AUSGABE
  fi
  cat $T | xargs java -ea ${program} > ${testresults_dir}/$B
set -o errexit
  cat AUSGABE > ${testresults_dir}/${B}_RET
done
rm AUSGABE

