#!/bin/bash
# Oliver Kullmann, 2.12.2012 (Swansea)

# Usage:

# RunTests program dir_with_tests

# Runs program via "java program" in the current
# directory, considering all testcases in dir_with_tests/Testcases,
# and comparing them with their solutions in dir_with_tests/Testresults.
# Storing the results in D/Evaluation/program_log_tests.
# dir_with_tests must be given as an absolute pathname.

set -o errexit
set -o nounset
set -o pipefail

script_name="RunTests"
version_number=0.1

errormsg="ERROR[${script_name}]:"

if [[ $# != 2 ]]; then
  echo "${errormsg} Precisely two arguments are needed:
 program dir_with_tests"
  exit 1
fi

program=$1
dir_with_tests=$2

evaldir="Evaluation"

logfile="${evaldir}/${program}_log_tests"
outputfile="${evaldir}/${program}_output"
difffile="${evaldir}/${program}_diff"

date > ${logfile}
if [[ ! -f "${program}.java" ]]; then
  echo " No ${program}.java."
  echo "No ${program}.java." >> ${logfile}
  exit 1
fi
for T in ${dir_with_tests}/Testcases/*; do
  B="$(basename $T)"
  echo -e "\nRUNNING $B" | tee -a ${logfile}
set +o errexit
  if [[ -s $T ]]; then
    cat $T | xargs bash -c 'java '"${program}"' "$@"; echo "$?" > AUSGABE ' -
    returnval=$(cat AUSGABE)
  else
    java ${program}
    returnval=$?
  fi
  cat ${T} | xargs java ${program} &>${outputfile}
set -o errexit
  comparison="${dir_with_tests}/Testresults/${B}"
  compret="$(cat ${dir_with_tests}/Testresults/${B}_RET)"
set +o errexit
  diff ${comparison} ${outputfile} &>${difffile}
  diffret=$?
set -o errexit
  if [[ ${diffret} != 0 ]]; then
    echo "Testfailure with output (observed vs. correct):" >> ${logfile}
    echo "------------" >> ${logfile}
    cat ${outputfile} >> ${logfile}
    echo "------------" >> ${logfile}
    cat ${comparison} >> ${logfile}
  fi
  if [[ ${returnval} != ${compret} ]]; then
    echo "Testfailure with exitcode: (observed vs. correct)" >> ${logfile}
    echo "${returnval} ${compret}" >> ${logfile}
  fi
  rm -f ${outputfile} ${difffile} AUSGABE
done

